### ISSUE TITLE
Dont see url

### ISSUE THREAD

**Issue by shahbharaz** [ElevenPaths/thethe#12]
Hi Devs

Cant see the url once i have loaded this up
Seems to be ok and all there in linux but no joy on the browser 
![image](https://user-images.githubusercontent.com/30074741/73855998-bf17f280-482c-11ea-8f1c-363bb8a8d43d.png)

**Comment by deibit** [comment]
Hi, would need a little more information to help you.

Did you try our installation instructions? https://github.com/ElevenPaths/thethe#installation

You should run "docker-compose up -d" from the root of the project. If everything was ok you should see all the containers running:

docker ps 

Thanks.
