### ISSUE TITLE
Parse protected IOC

### ISSUE THREAD

**Issue by jpalanco** [ElevenPaths/thethe#19]
Convert hxxp to http and [.] to . before parsing. For example:

- hxxps://pastebin[.]com/QM5ttnx3 to https://pastebin.com/QM5ttnx3
- 10.0.0[.]1 to 10.0.0.1

**Comment by jpalanco** [comment]
It would be awesome if it's possible to parse multiple IOC per line and remove the garbage

Check this https://github.com/armbues/ioc_parser

**Comment by deibit** [comment]
These two were Implemented in https://github.com/ElevenPaths/thethe/commit/2ee0b9b8c25bbccf7ff9c7df8255b473096523fe

Thanks for the suggestions.
