### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by jpalanco** [ElevenPaths/thethe#23]
Sometimes an investigations change the scope, so it could be useful to edit the name of the project

**Comment by deibit** [comment]
Added in  https://github.com/ElevenPaths/thethe_frontend/commit/71abef852f3af0d6f89795c78db8721ff9d475e4 and https://github.com/ElevenPaths/thethe_server/commit/cb3373497e0eaf0a0e3283fa5f87d95f61315868
