### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by rmsferreira** [ElevenPaths/thethe#7]
Hi.

I setup TheThe and see all img running, but when I access to the Server the user admin with the password admin wont work.

Thanks

**Comment by deibit** [comment]
Hi, please try with the last update we pushed https://github.com/ElevenPaths/thethe/commit/9abe8644b4c70a81087cf30c3f25b82fa10e7c57 

Let us know if it fixed the issue. btw, was your thethe server in a non-localhost set up?

Thanks!

**Comment by Luiska12** [comment]
Same problem here, I can access admin/admin on the localhost, but on a non-localhost it shows the error related to the login.
 
Will try the latest update to see what will happen.

**Comment by Luiska12** [comment]
Problem solved on my environment with the update.

**Comment by deibit** [comment]
> Problem solved on my environment with the update.

Thanks for the news.
